site_name: Triality Test Suite

theme:
  name: material

nav:
  - Home: index.md
  - Replication: replicate.md
  - API: api.md
  - Theory: theory.md
  - Discipline: discipline.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true