name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Triality version / git SHA
      placeholder: v11.0.0 / abc1234
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include commands, configs, and minimal data slice if possible.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Minimal reproduction
      description: Smallest command + config to reproduce.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      render: shell
    validations:
      required: false