name: triality
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - scipy>=1.12
  - matplotlib>=3.8
  - pandas>=2.2
  - pyyaml>=6.0
  - statsmodels>=0.14
  - scikit-learn>=1.4
  - numba>=0.59
  - rich>=13.7
  - jinja2>=3.1
  - pip
  - pip:
      - pytest>=8.0